### PR TITLE
Update Insane_Korean translation

### PR DESCRIPTION
**Pull request by eidals224**
한국 정발 용어로 수정
Modified to Korean official release terms

### CODE REVIEW

**Review by ysakasin — CHANGES_REQUESTED** [review]
The unit test is failed. Please also update `test/data/Insane_Korean.toml` .

https://github.com/eidals224/BCDice/blob/patch-1/test/data/Insane_Korean.toml

**Comment by eidals224** [comment]
thank you. I just updated test/data/Insane_Korean.toml

**Comment by ysakasin** [comment]
It is still failed. Please check [output](https://github.com/bcdice/BCDice/actions/runs/6826189403/job/18566031747?pr=647) and fix difference between translation data and test data.

**Comment by eidals224** [comment]
Oh, I just fixed differences!

**Review by ysakasin — APPROVED** [review]

**Comment by ysakasin** [comment]
@eidals224 Thank you for updating! It is merged.

**Pull request merged**
